.Dd June 26, 2026
.Dt LIBFSHFS 3
.Os
.Sh NAME
.Nm libfshfs.h
.Nd Library to access the Hierarchical File System (HFS) format
.Sh SYNOPSIS
.In libfshfs.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libfshfs_get_version
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_get_access_flags_read
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_get_codepage
.Fa "int *codepage"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_set_codepage
.Fa "int codepage"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_check_volume_signature
.Fa "const char *filename"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libfshfs_check_volume_signature_wide
.Fa "const wchar_t *filename"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libfshfs_check_volume_signature_file_io_handle
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libfshfs_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_notify_set_stream
.Fa "FILE *stream"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_notify_stream_open
.Fa "const char *filename"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_notify_stream_close
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libfshfs_error_free
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_error_fprint
.Fa "libfshfs_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_error_sprint
.Fa "libfshfs_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_error_backtrace_fprint
.Fa "libfshfs_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_error_backtrace_sprint
.Fa "libfshfs_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
Volume functions
.nf
.Ft int
.Fo libfshfs_volume_initialize
.Fa "libfshfs_volume_t **volume"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_free
.Fa "libfshfs_volume_t **volume"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_signal_abort
.Fa "libfshfs_volume_t *volume"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_open
.Fa "libfshfs_volume_t *volume"
.Fa "const char *filename"
.Fa "int access_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_close
.Fa "libfshfs_volume_t *volume"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_utf8_name_size
.Fa "libfshfs_volume_t *volume"
.Fa "size_t *utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_utf8_name
.Fa "libfshfs_volume_t *volume"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_utf16_name_size
.Fa "libfshfs_volume_t *volume"
.Fa "size_t *utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_utf16_name
.Fa "libfshfs_volume_t *volume"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_root_directory
.Fa "libfshfs_volume_t *volume"
.Fa "libfshfs_file_entry_t **file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_file_entry_by_identifier
.Fa "libfshfs_volume_t *volume"
.Fa "uint32_t identifier"
.Fa "libfshfs_file_entry_t **file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_file_entry_by_utf8_path
.Fa "libfshfs_volume_t *volume"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfshfs_file_entry_t **file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_volume_get_file_entry_by_utf16_path
.Fa "libfshfs_volume_t *volume"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfshfs_file_entry_t **file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libfshfs_volume_open_wide
.Fa "libfshfs_volume_t *volume"
.Fa "const wchar_t *filename"
.Fa "int access_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libfshfs_volume_open_file_io_handle
.Fa "libfshfs_volume_t *volume"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "int access_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
File entry functions
.nf
.Ft int
.Fo libfshfs_file_entry_free
.Fa "libfshfs_file_entry_t **file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_parent_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *parent_identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_parent_file_entry
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "libfshfs_file_entry_t **parent_file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_link_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *link_identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_creation_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *hfs_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_modification_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *hfs_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_entry_modification_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *hfs_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_access_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *hfs_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_backup_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *hfs_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_added_time
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int32_t *posix_time"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_file_mode
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint16_t *file_mode"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_number_of_links
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *number_of_links"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_owner_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *owner_identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_group_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *group_identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_device_identifier
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *device_identifier"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_device_number
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint32_t *major_device_number"
.Fa "uint32_t *minor_device_number"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf8_name_size
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "size_t *utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf8_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf16_name_size
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "size_t *utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf16_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf8_symbolic_link_target_size
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "size_t *utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf8_symbolic_link_target
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf16_symbolic_link_target_size
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "size_t *utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_utf16_symbolic_link_target
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_has_resource_fork
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_resource_fork
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "libfshfs_data_stream_t **data_stream"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_number_of_extended_attributes
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int *number_of_extended_attributes"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_extended_attribute_by_index
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int extended_attribute_index"
.Fa "libfshfs_extended_attribute_t **extended_attribute"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_has_extended_attribute_by_utf8_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_has_extended_attribute_by_utf16_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_extended_attribute_by_utf8_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfshfs_extended_attribute_t **extended_attribute"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_extended_attribute_by_utf16_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfshfs_extended_attribute_t **extended_attribute"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_number_of_sub_file_entries
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int *number_of_sub_file_entries"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_sub_file_entry_by_index
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int sub_file_entry_index"
.Fa "libfshfs_file_entry_t **sub_file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_sub_file_entry_by_utf8_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfshfs_file_entry_t **sub_file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_sub_file_entry_by_utf16_name
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfshfs_file_entry_t **sub_file_entry"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_file_entry_read_buffer
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_file_entry_read_buffer_at_offset
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "off64_t offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libfshfs_file_entry_seek_offset
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_offset
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "off64_t *offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_size
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "size64_t *size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_number_of_extents
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int *number_of_extents"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_file_entry_get_extent_by_index
.Fa "libfshfs_file_entry_t *file_entry"
.Fa "int extent_index"
.Fa "off64_t *extent_offset"
.Fa "size64_t *extent_size"
.Fa "uint32_t *extent_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Data stream functions
.nf
.Ft int
.Fo libfshfs_data_stream_free
.Fa "libfshfs_data_stream_t **data_stream"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_data_stream_read_buffer
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_data_stream_read_buffer_at_offset
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "off64_t offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libfshfs_data_stream_seek_offset
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_data_stream_get_offset
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "off64_t *offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_data_stream_get_size
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "size64_t *size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_data_stream_get_number_of_extents
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "int *number_of_extents"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_data_stream_get_extent_by_index
.Fa "libfshfs_data_stream_t *data_stream"
.Fa "int extent_index"
.Fa "off64_t *extent_offset"
.Fa "size64_t *extent_size"
.Fa "uint32_t *extent_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Pp
Extended attribute functions
.nf
.Ft int
.Fo libfshfs_extended_attribute_free
.Fa "libfshfs_extended_attribute_t **extended_attribute"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_utf8_name_size
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "size_t *utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_utf8_name
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_utf16_name_size
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "size_t *utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_utf16_name
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_extended_attribute_read_buffer
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfshfs_extended_attribute_read_buffer_at_offset
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "off64_t offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libfshfs_extended_attribute_seek_offset
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_offset
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "off64_t *offset"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_size
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "size64_t *size"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_number_of_extents
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "int *number_of_extents"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfshfs_extended_attribute_get_extent_by_index
.Fa "libfshfs_extended_attribute_t *extended_attribute"
.Fa "int extent_index"
.Fa "off64_t *extent_offset"
.Fa "size64_t *extent_size"
.Fa "uint32_t *extent_flags"
.Fa "libfshfs_error_t **error"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libfshfs_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libfshfs.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
libfshfs can be compiled with wide character support (wchar_t).
.sp
To compile libfshfs with wide character support use:
.Ar ./configure --enable-wide-character-type
 or define:
.Ar _UNICODE
 or
.Ar UNICODE
 during compilation.
.sp
.Ar LIBFSHFS_WIDE_CHARACTER_TYPE
 in libfshfs/features.h can be used to determine if libfshfs was compiled with \
wide character support.
.Sh SEE ALSO
.In libfshfs.h
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libfshfs/issues
.Sh COPYRIGHT
Copyright (C) 2009-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
